[package]
name = "polygon-arbitrage-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { version = "2.0", features = ["abigen"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
config = "0.13"
dotenv = "0.15"
eyre = "0.6"
